### PR TITLE
Add description for HTML Sanitizer API

### PR DESCRIPTION
**Pull request by 0xedward**
#### Test plan
1. `make`
2. `python3 -m http.server`
3. Go to http://0.0.0.0:8000

image

### CODE REVIEW

**Comment by mikewest** [comment]
Can you rebase this on top of main?

**Comment by mikewest** [comment]
(And maybe just update the template; `index.html` probably wouldn't be in this repo if I expected anyone other than me to deploy this site. :) )

**Comment by 0xedward** [comment]
@mikewest, I rebased on top of main and excluded all commits other than the changes to `template.html` :)

**Review by mikewest — APPROVED** [review]

**Comment by mikewest** [comment]
Thanks!

**Pull request merged**
